---
title: "test"
output: html_document
---

```{r, message = F, warning = F}
library(here)
library(readr)
library(dplyr)
library(purrr)
library(tidyr)
library(ggplot2)
library(lubridate)
```

```{r}
washpo <-
    read_csv(here("data", "washpo.csv")) %>%
    select(-id, -name, -longitude, -latitude, -is_geocoding_exact, -city) %>%
    mutate(year = year(date),
           month = month(date),
           day = day(date)) %>%
    select(-date)
```

```{r}
washpo %>%
    select(where(is.numeric)) %>%
    pivot_longer(everything()) %>%
    ggplot(aes(x = value)) +
    geom_histogram(bins = 25) +
    facet_wrap(~name, scales = "free_x") +
    theme_bw()

summary(washpo$age)
```

```{r}
washpo %>%
    select(c(!where(is.numeric), -armed, -state, -day, -month, -year)) %>%
    pivot_longer(everything(),
                 values_transform = list(value = as.character)) %>%
    ggplot(aes(x = value)) +
    geom_bar() +
    facet_wrap(~name, scales = "free") +
    theme_bw()
```

```{r}
washpo %>%
    select(state) %>%
    group_by(state) %>%
    count(state) %>%
    ggplot(aes(x = reorder(state, n), n)) +
    geom_bar(stat = "identity") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 290, hjust = 0))
```

```{r}
washpo %>%
    select(day, month, year) %>%
    pivot_longer(everything()) %>%
    ggplot(aes(x = value)) +
    geom_bar() +
    facet_wrap(~name, scales = "free") +
    theme_bw()
```

```{r}
washpo %>%
    select(armed) %>%
    count(armed) %>%
    mutate(prcnt = n / sum(n),
           armedNew = if_else(prcnt < 0.01, "other", armed)) %>%
    group_by(armedNew) %>%
    summarise(n = sum(n)) %>%
    ungroup() %>%
    ggplot(aes(x = reorder(armedNew, n), y = n)) +
    geom_bar(stat = "identity") +
    theme_bw() +
    coord_flip()
```
